version: "3.8"

services:
  backend:
    build: .
    container_name: telehealth_backend
    ports:
      - "8000:8000"   # Expose FastAPI server port
    env_file: .env
    depends_on:
      - redis
    volumes:
      # Bind mount your local SQLite file or folder for persistence
      - ./test:/app/test

  redis:
    image: redis:7-alpine
    container_name: telehealth_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--notify-keyspace-events", "Ex"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
