version: "3.9"

services:
  backend:
    build: .
    container_name: telehealth_backend
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: telehealth_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--notify-keyspace-events", "Ex"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
